services:
  stackzero:
    image: ghcr.io/robertfent/stackzero:staging
    command: ["npm", "run", "start-local"]
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./app:/stackzero/app
      - ./static:/stackzero/static
      - ./data:/stackzero/data
      # - ./core:/stackzero/core # enable this line after copying content of the folder to local machine to overwrite core logic manually
