services:
  stackzero:
    image: ghcr.io/robertfent/stackzero:v1.0.0-staging
    command: ["npm", "run", "start-local"]
    ports:
      - 3000:3000
    environment:
      - FORKS=1
      - NODE_ENV=development
      - DB_LOCATION=./data/testingapp.db
      - PORT=3000
    volumes:
      - ./app:/stackzero/app
      - ./static:/stackzero/static
      - ./data:/stackzero/data
      # - ./core:/stackzero/core # enable this line after copying content of the folder to local machine to overwrite core logic manually
